"""Group accepted lessons by topic and emit ``learned-<topic>/SKILL.md`` drafts.

Drafts are always written under ``--out`` — never directly into a real
``.devin/skills/`` directory unless the caller passes ``--apply``
(``emit_drafts(..., apply=True)``). Topic clustering is a deterministic
keyword table; anything unmatched lands in ``geral``.
"""

from __future__ import annotations

import re
from datetime import datetime, timezone
from pathlib import Path

from .review import Verdict

DEFAULT_TOPIC = "geral"

# Order matters: first matching bucket wins. ``security`` comes before
# ``git-workflow`` so "don't commit secrets" lands where it belongs.
TOPIC_KEYWORDS: dict[str, tuple[str, ...]] = {
    "security": ("secret", "token", "password", "credential", "api key", ".env", "private key"),
    "testing": ("test", "pytest", "coverage", "assert", "tdd", "unittest"),
    "git-workflow": ("commit", "rebase", "merge", "branch", "push", "pull request", "checkout", "stash"),
    "docs": ("changelog", "status.md", "readme", "documentation", "docs", "comment", "docstring"),
    "style": ("lint", "format", "ruff", "black", "prettier", "style", "type hint", "typing"),
    "python": ("python", "pip", "venv", "module", "package"),
    "shell": ("bash", "shell", "terminal", "command line"),
}

def _kw_rx(keyword: str) -> re.Pattern[str]:
    # Prefix match: "secret" catches "secrets", "commit" catches
    # "committing". The left boundary is skipped for keywords that start
    # with punctuation (".env") so they match mid-path too.
    pattern = re.escape(keyword)
    if keyword[0].isalnum() or keyword[0] == "_":
        pattern = r"(?<!\w)" + pattern
    return re.compile(pattern, re.IGNORECASE)


_TOPIC_RXES: dict[str, tuple[re.Pattern[str], ...]] = {
    topic: tuple(_kw_rx(kw) for kw in keywords)
    for topic, keywords in TOPIC_KEYWORDS.items()
}


class LiveSkillsDirError(RuntimeError):
    """Refusing to write drafts into a live ``.devin/skills`` without --apply."""


def topic_for(text: str) -> str:
    """Deterministic keyword bucket; falls back to ``geral``."""
    for topic, rxes in _TOPIC_RXES.items():
        if any(rx.search(text) for rx in rxes):
            return topic
    return DEFAULT_TOPIC


def group_by_topic(verdicts: list[Verdict]) -> dict[str, list[Verdict]]:
    """Cluster accepted verdicts by topic (insertion order preserved)."""
    groups: dict[str, list[Verdict]] = {}
    for v in verdicts:
        if not v.accepted:
            continue
        groups.setdefault(topic_for(v.candidate.text), []).append(v)
    return groups


def _iso_date(ms: int) -> str:
    return datetime.fromtimestamp(ms / 1000, tz=timezone.utc).date().isoformat()


def render_skill(topic: str, verdicts: list[Verdict]) -> str:
    """Render the SKILL.md draft body for one topic."""
    ordered = sorted(
        verdicts, key=lambda v: (v.candidate.created_at, v.candidate.text)
    )
    day = max(_iso_date(v.candidate.created_at) for v in ordered)
    lines = [
        "---",
        f"name: learned-{topic}",
        f'description: "Lessons about {topic} auto-extracted from Devin sessions — review before enabling"',
        "triggers:",
        "  - model",
        "---",
        "",
        f"# Learned lessons: {topic}",
        "",
        "> Draft generated by `devin-learning`. Review before promoting into",
        "> `.devin/skills/` (promotion requires `--apply`).",
        "",
        "## Lessons",
        "",
    ]
    lines += [
        f"- ({_iso_date(v.candidate.created_at)}) {v.candidate.text}"
        for v in ordered
    ]
    lines += [
        "",
        "## Changelog",
        "",
        f"- v1 ({day}): {len(ordered)} lesson(s)",
        "",
    ]
    return "\n".join(lines)


def _is_live_skills_dir(out_dir: Path) -> bool:
    parts = out_dir.resolve().parts
    return any(
        parts[i] == ".devin" and i + 1 < len(parts) and parts[i + 1] == "skills"
        for i in range(len(parts) - 1)
    )


def emit_drafts(
    verdicts: list[Verdict], out_dir: str | Path, *, apply: bool = False
) -> list[Path]:
    """Write ``learned-<topic>/SKILL.md`` drafts for accepted verdicts.

    Only ever writes inside ``out_dir``. Refuses a live ``.devin/skills``
    target unless ``apply=True``. Returns the written paths, sorted.
    """
    out = Path(out_dir).resolve()
    if _is_live_skills_dir(out) and not apply:
        raise LiveSkillsDirError(
            f"{out}: target is a live .devin/skills directory — "
            "re-run with --apply to promote drafts"
        )
    written: list[Path] = []
    for topic, group in group_by_topic(verdicts).items():
        skill_dir = out / f"learned-{topic}"
        skill_dir.mkdir(parents=True, exist_ok=True)
        target = skill_dir / "SKILL.md"
        target.write_text(render_skill(topic, group), encoding="utf-8")
        written.append(target)
    return sorted(written)
